# Generated by Django 4.2.7 on 2025-12-02 18:19

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant unique de l'utilisateur", primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text="Adresse email unique de l'utilisateur", max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Numéro de téléphone tunisien', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format tunisien: +216XXXXXXXX ou 216XXXXXXXX', regex='^\\+?216\\d{8}$')])),
                ('name', models.CharField(help_text="Nom complet de l'utilisateur", max_length=100)),
                ('otp_secret', models.CharField(blank=True, help_text='Secret pour la génération OTP', max_length=32)),
                ('is_2fa_enabled', models.BooleanField(default=True, help_text='Authentification à deux facteurs activée')),
                ('failed_login_attempts', models.IntegerField(default=0, help_text='Nombre de tentatives de connexion échouées')),
                ('account_locked_until', models.DateTimeField(blank=True, help_text="Date jusqu'à laquelle le compte est verrouillé", null=True)),
                ('last_password_change', models.DateTimeField(auto_now_add=True, help_text='Date du dernier changement de mot de passe')),
                ('password_reset_token', models.CharField(blank=True, help_text='Token pour la réinitialisation du mot de passe', max_length=100)),
                ('password_reset_token_expires', models.DateTimeField(blank=True, help_text="Date d'expiration du token de réinitialisation", null=True)),
                ('account_status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('locked', 'Verrouillé'), ('closed', 'Fermé')], default='active', help_text='Statut actuel du compte', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du compte')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom du bénéficiaire', max_length=100)),
                ('iban', models.CharField(help_text='IBAN du bénéficiaire', max_length=34)),
                ('bank_name', models.CharField(help_text='Nom de la banque', max_length=100)),
                ('bank_type', models.CharField(choices=[('same', 'Même Banque'), ('national', 'Banque Nationale'), ('international', 'Banque Étrangère')], default='same', help_text='Type de banque', max_length=15)),
                ('swift_code', models.CharField(blank=True, help_text='Code SWIFT (pour les virements internationaux)', max_length=11)),
                ('status', models.CharField(choices=[('pending_verification', 'En attente de vérification'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], default='pending_verification', help_text='Statut de vérification du bénéficiaire', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date d'ajout du bénéficiaire")),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('owner', models.ForeignKey(help_text='Utilisateur propriétaire de ce bénéficiaire', on_delete=django.db.models.deletion.CASCADE, related_name='bank_beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'verbose_name_plural': 'Bénéficiaires',
                'db_table': 'beneficiaries',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['owner', 'status'], name='beneficiari_owner_i_eb43cb_idx'), models.Index(fields=['iban'], name='beneficiari_iban_1eb4b1_idx')],
                'unique_together': {('owner', 'iban')},
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Main Account', help_text='Nom du compte (ex: Compte Principal)', max_length=100)),
                ('iban', models.CharField(db_index=True, help_text='IBAN du compte (format TN59XXXXXXXXXXXXXXXXXX)', max_length=34, unique=True)),
                ('account_type', models.CharField(choices=[('checking', 'Compte Courant'), ('savings', 'Compte Épargne')], default='checking', help_text='Type de compte', max_length=10)),
                ('balance', models.DecimalField(decimal_places=3, default=0.0, help_text='Solde du compte en TND', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='TND', help_text='Devise du compte', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('closed', 'Fermé')], default='active', help_text='Statut du compte', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du compte')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('last_transaction_date', models.DateTimeField(blank=True, help_text='Date de la dernière transaction', null=True)),
                ('user', models.ForeignKey(help_text='Propriétaire du compte', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte Bancaire',
                'verbose_name_plural': 'Comptes Bancaires',
                'db_table': 'bank_accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['iban'], name='bank_accoun_iban_9fb624_idx'), models.Index(fields=['user', 'status'], name='bank_accoun_user_id_cf0c2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('failed_login', 'Tentative de connexion échouée'), ('password_change', 'Changement de mot de passe'), ('password_reset', 'Réinitialisation de mot de passe'), ('profile_update', 'Mise à jour du profil'), ('transfer_initiated', 'Virement initié'), ('transfer_completed', 'Virement complété'), ('transfer_failed', 'Virement échoué'), ('transfer_cancelled', 'Virement annulé'), ('beneficiary_added', 'Bénéficiaire ajouté'), ('beneficiary_updated', 'Bénéficiaire modifié'), ('beneficiary_deleted', 'Bénéficiaire supprimé'), ('account_locked', 'Compte verrouillé'), ('account_unlocked', 'Compte déverrouillé'), ('suspicious_activity', 'Activité suspecte'), ('rate_limit_exceeded', 'Limite de taux dépassée')], help_text="Type d'action effectuée", max_length=50)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('failed', 'Échec'), ('warning', 'Avertissement')], default='success', help_text="Résultat de l'action", max_length=20)),
                ('description', models.TextField(blank=True, help_text="Description détaillée de l'action")),
                ('amount', models.DecimalField(blank=True, decimal_places=3, help_text='Montant concerné (pour les transactions)', max_digits=15, null=True)),
                ('ip_address', models.GenericIPAddressField(help_text="Adresse IP de l'utilisateur")),
                ('user_agent', models.TextField(help_text='User agent du navigateur')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Date et heure de l'action")),
                ('user', models.ForeignKey(help_text="Utilisateur ayant effectué l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'Audit",
                'verbose_name_plural': "Journaux d'Audit",
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_logs_timesta_e93820_idx'), models.Index(fields=['user', 'action'], name='audit_logs_user_id_d685f3_idx'), models.Index(fields=['action', 'status'], name='audit_logs_action_d96607_idx'), models.Index(fields=['ip_address'], name='audit_logs_ip_addr_919cb4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_status'], name='users_account_33da0c_idx'),
        ),
    ]
