# Generated by Django 4.2.7 on 2025-12-02 18:19

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLimit',
            fields=[
                ('user', models.OneToOneField(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='transaction_limit', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('daily_transfer_limit', models.DecimalField(decimal_places=3, default=Decimal('10000.000'), help_text='Limite de transfert quotidienne en TND', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('single_transfer_limit', models.DecimalField(decimal_places=3, default=Decimal('5000.000'), help_text='Limite par transaction en TND', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('daily_transfer_used', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text="Montant déjà utilisé aujourd'hui", max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('last_reset_date', models.DateField(auto_now_add=True, help_text='Date de dernière réinitialisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
            ],
            options={
                'verbose_name': 'Limite de Transaction',
                'verbose_name_plural': 'Limites de Transaction',
                'db_table': 'transaction_limits',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('transfer', 'Virement'), ('deposit', 'Dépôt'), ('withdrawal', 'Retrait')], help_text='Type de transaction', max_length=10)),
                ('amount', models.DecimalField(decimal_places=3, help_text='Montant de la transaction', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('currency', models.CharField(default='TND', help_text='Devise de la transaction', max_length=3)),
                ('description', models.TextField(blank=True, help_text='Description ou motif de la transaction')),
                ('reference_number', models.CharField(db_index=True, help_text='Numéro de référence unique (ex: TXN-20241203-123456)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('initiated', 'Initié'), ('otp_sent', 'OTP Envoyé'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', help_text='Statut actuel de la transaction', max_length=15)),
                ('initiated_at', models.DateTimeField(auto_now_add=True, help_text="Date d'initiation de la transaction")),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date de complétion de la transaction', null=True)),
                ('ip_address', models.GenericIPAddressField(help_text="Adresse IP de l'utilisateur")),
                ('user_agent', models.TextField(help_text='User agent du navigateur')),
                ('otp_verified', models.BooleanField(default=False, help_text='OTP vérifié avec succès')),
                ('confirmation_email_sent', models.BooleanField(default=False, help_text='Email de confirmation envoyé')),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur si la transaction a échoué")),
                ('beneficiary', models.ForeignKey(blank=True, help_text='Bénéficiaire du virement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.beneficiary')),
                ('from_account', models.ForeignKey(help_text='Compte source du virement', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='accounts.bankaccount')),
                ('to_account', models.ForeignKey(blank=True, help_text='Compte destination (si interne)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='accounts.bankaccount')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['-initiated_at'], name='transaction_initiat_62592a_idx'), models.Index(fields=['reference_number'], name='transaction_referen_dda4a8_idx'), models.Index(fields=['status'], name='transaction_status_505a2f_idx'), models.Index(fields=['from_account', '-initiated_at'], name='transaction_from_ac_b9228f_idx'), models.Index(fields=['to_account', '-initiated_at'], name='transaction_to_acco_29e8a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=3, help_text='Montant à transférer', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('description', models.TextField(blank=True, help_text='Description de la transaction')),
                ('otp_code', models.CharField(help_text='Code OTP généré', max_length=6)),
                ('otp_expires_at', models.DateTimeField(help_text="Date d'expiration de l'OTP")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('ip_address', models.GenericIPAddressField(help_text="Adresse IP de l'utilisateur")),
                ('user_agent', models.TextField(help_text='User agent du navigateur')),
                ('is_consumed', models.BooleanField(default=False, help_text='OTP déjà utilisé')),
                ('beneficiary', models.ForeignKey(help_text='Bénéficiaire de la transaction', on_delete=django.db.models.deletion.CASCADE, to='accounts.beneficiary')),
                ('from_account', models.ForeignKey(help_text='Compte source', on_delete=django.db.models.deletion.CASCADE, to='accounts.bankaccount')),
                ('user', models.ForeignKey(help_text='Utilisateur initiant la transaction', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction en Attente',
                'verbose_name_plural': 'Transactions en Attente',
                'db_table': 'pending_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='pending_tra_user_id_a73323_idx'), models.Index(fields=['otp_expires_at'], name='pending_tra_otp_exp_d256d5_idx')],
            },
        ),
    ]
